### PR TITLE
Upgrade to autoRIFT 1.3.0

### PR DESCRIPTION
**Pull request by jhkennedy**

### CODE REVIEW

**Comment by jhkennedy** [comment]
Ran a Landsat pair and got the expected product with the expected metadata changes; I think this is ready for review -- I'll do more testing in develop before release

**Comment by asjohnston-asf** [comment]
Looks like hyp3_autorift/vend/README.md changes are still outstanding, at least to update the source version number

**Comment by jhkennedy** [comment]
@asjohnston-asf good catch! Updated.

**Comment by asjohnston-asf** [comment]
vend/netcdf_output.py should be updated to the latest vendor version, as well

**Review by asjohnston-asf — APPROVED** [review]

**Pull request merged**
